### ISSUE TITLE
Where does program node-kill come from?

### ISSUE THREAD

**Issue by ibigbug** [aliyun-node/commands#8]
I install commands manually and did not find the `node-kill` executable used in the scripts.

How can I get this program?

**Comment by joyeecheung** [comment]
This executable comes with the alinode runtime. You need to install our distribution  to use it.

**Comment by JacksonTian** [comment]
Use `tnvm install alinode-vx.x.x`, the `node-kill` executable exists with `node`.

**Comment by ibigbug** [comment]
Thanks for reply. I'll try it this week.

**Comment by ibigbug** [comment]
It works now!

I think it can be easier to use alinode if you can provide the binary package direct download link to omit the `tnvm` installation step.

**Comment by joyeecheung** [comment]
The releases are all under https://alinode.aliyun.com/dist/new-alinode/ at the moment (though subject to change in the future).

**Comment by ibigbug** [comment]
That's cool. :D
